/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: b3bd66acd4c52361557878b10e1df76f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		GEMINI_API_KEY: string;
		GEMINI_MODEL?: string;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_API_KEY">> {}
}
